import './globals.css'
import { Jost } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const jost = Jost({ weight: '600', subsets: ['latin'], display: 'swap' })

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en" className={jost.className}>
      <body>{children}</body>
    </html>
  )
}
